<?php

namespace ContainerCb9nmVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IN37pjnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iN37pjn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iN37pjn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'service' => ['privates', 'App\\Services\\TestService', 'getTestServiceService', true],
        ], [
            'service' => 'App\\Services\\TestService',
        ]);
    }
}
