#index:
#    path: /
#    controller: App\Controller\DefaultController::index

add-user:
  path: /add-user
  controller: App\Controller\UserController::index

add-post:
  path: /add-post
  controller: App\Controller\MainController::index