#index:
#    path: /
#    controller: App\Controller\DefaultController::index

main:
  path: /main
  controller: App\Controller\MainController::index

add-post:
  path: /add-post
  controller: App\Controller\AddPostController::addPost

login:
  path: /add-post
  controller: App\Controller\SecurityController::login