<?php


namespace App\Form;


use App\Entity\Post;
use phpDocumentor\Reflection\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddPostType extends AbstractType
{
    //function for creating a form
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('title', TextType::class, [
                'attr' =>[
                    'class' => 'input'
                ],
                'label' => 'Title',
                'label_attr' => ['class' => 'label']
            ])
//            ->add('user')
            ->add('content', TextareaType::class, [
                'attr' =>[
                    'class' => 'input'
                ],
                'label_attr' => ['class' => 'label']
            ]);
    }

    // function to bind form with DB
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class
        ]);
    }


}