<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGhs5OXr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGhs5OXr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGhs5OXr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGhs5OXr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGhs5OXr\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ghs5OXr',
    'container.build_id' => '78c56cb0',
    'container.build_time' => 1602369697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGhs5OXr');
