<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Kr2q5x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Kr2q5x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4Kr2q5x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4Kr2q5x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4Kr2q5x\App_KernelDevDebugContainer([
    'container.build_hash' => '4Kr2q5x',
    'container.build_id' => '1c7b4f32',
    'container.build_time' => 1602979891,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Kr2q5x');
