<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCb9nmVu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCb9nmVu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCb9nmVu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCb9nmVu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCb9nmVu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cb9nmVu',
    'container.build_id' => '4b2a8fbe',
    'container.build_time' => 1602456712,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCb9nmVu');
